AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  b2201-sam-demo

  Sample SAM Template for b2201-sam-demo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: python3.8


Resources:
  B2201SamFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: b2201_sam/
      Handler: app.lambda_handler
      Architectures:
        - x86_64
      Role: arn:aws:iam::666680140343:role/service-role/myLambdaRole
      Events:
        B2201Sam:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get-info
            Method: get
  B2201SamFunction2:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: b2201_sam/
      Handler: lambda2.lambda_handler
      Architectures:
        - x86_64
      Role: arn:aws:iam::666680140343:role/service-role/myLambdaRole
      Events:
        B2201Sam:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /submit-info
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  B2201SamApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-info/"
  B2201SamFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt B2201SamFunction.Arn
  B2201SamFunctionIamRole:
    Description: "Implicit IAM Role created for B2201SamFunction"
    Value: !GetAtt B2201SamFunction.Arn
